sudo: true
dist: trusty
language: ruby
rvm:
  - 2.3

services:
  - docker

jobs:
  include:
    - stage: rake build
      install: true
      script:
      - docker run -v $PWD:/tf-test/module --rm microsoft/terraform-test rake -f ../Rakefile build
    - stage: rake e2e
      install: true
      script:
      - docker run -v $PWD:/tf-test/module -e ARM_CLIENT_ID -e ARM_TENANT_ID -e ARM_SUBSCRIPTION_ID -e ARM_CLIENT_SECRET -e ARM_TEST_LOCATION -e ARM_TEST_LOCATION_ALT --rm microsoft/terraform-test rake -f ../Rakefile e2e